name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # This will trigger on changes to the main branch
    paths:
      - Dockerfile  # Triggers only when Dockerfile changes

jobs:
  build:
    runs-on: ubuntu-latest  # Run on the latest Ubuntu environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # GitHub secret for Docker Hub username
          password: ${{ secrets.DOCKER_PASSWORD }}  # GitHub secret for Docker Hub password

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: aayustha/figlet:latest  # Tag your image

